//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aministration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HumidityCalculatorEntities : DbContext
    {
        public HumidityCalculatorEntities()
            : base("name=HumidityCalculatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Bassin> Bassins { get; set; }
        public virtual DbSet<Observateur> Observateurs { get; set; }
        public virtual DbSet<RelativeHumidity> RelativeHumidities { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<User> Users { get; set; }

        public static implicit operator HumidityCalculatorEntities(RelativeHumidity v)
        {
            throw new NotImplementedException();
        }
    }
}
