//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aministration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Observateur()
        {
            this.RelativeHumidities = new HashSet<RelativeHumidity>();
        }
    
        public int ObservateurId { get; set; }
        public string NomPrenomObservateur { get; set; }
        public int StationId { get; set; }
    
        public virtual Station Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelativeHumidity> RelativeHumidities { get; set; }
    }
}
